services:
  config-server:
    build:
      context: ./services/config-server
    ports:
      - "8888:8888"
    networks:
      - jaggery-net

  discovery-server:
    build:
      context: ./services/discovey-server
    ports:
      - "8761:8761"
    depends_on:
      - config-server
    networks:
      - jaggery-net
    command: ["./wait-for-it.sh", "config-server:8888", "--", "java", "-jar", "discovery-server.jar"]

  api-gateway:
    build:
      context: ./services/api-gateway
    ports:
      - "8222:8222"
    depends_on:
      - config-server
      - discovery-server
    networks:
      - jaggery-net
    command: ["./wait-for-it.sh", "discovery-server:8761", "--", "java", "-jar", "api-gateway.jar"]

  auth-service:
    build:
      context: ./services/auth-service
    ports:
      - "9090:9090"
    depends_on:
      - config-server
      - discovery-server
    networks:
      - jaggery-net
    command: ["./wait-for-it.sh", "discovery-server:8761", "--", "java", "-jar", "auth-service.jar"]

  customer-service:
    build:
      context: ./services/customer-service
    ports:
      - "8081:8081"
    depends_on:
      - config-server
      - discovery-server
    networks:
      - jaggery-net
    command: ["./wait-for-it.sh", "discovery-server:8761", "--", "java", "-jar", "customer-service.jar"]

  product-service:
    build:
      context: ./services/product-service
    ports:
      - "8082:8082"
    depends_on:
      - config-server
      - discovery-server
    networks:
      - jaggery-net
    command: ["./wait-for-it.sh", "discovery-server:8761", "--", "java", "-jar", "product-service.jar"]

  order-service:
    build:
      context: ./services/order-service
    ports:
      - "8084:8084"
    depends_on:
      - config-server
      - discovery-server
    networks:
      - jaggery-net
    command: ["./wait-for-it.sh", "discovery-server:8761", "--", "java", "-jar", "order-service.jar"]

  payment-service:
    build:
      context: ./services/payment-service
    ports:
      - "8085:8085"
    depends_on:
      - config-server
      - discovery-server
    networks:
      - jaggery-net
    command: ["./wait-for-it.sh", "discovery-server:8761", "--", "java", "-jar", "payment-service.jar"]

  notification-service:
    build:
      context: ./services/notification-service
    ports:
      - "8083:8083"
    depends_on:
      - config-server
      - discovery-server
    networks:
      - jaggery-net
    command: ["./wait-for-it.sh", "discovery-server:8761", "--", "java", "-jar", "notification-service.jar"]


networks:
  jaggery-net :
    driver: bridge